# database connectivity property
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservicedb
    username: root
    password: Jagadish@99
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  #   application name
  application:
    name: USER-SERVICE


# server port property
server:
  port: 8082

# eureka client property
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance: localhost


