
server:
  port: 8086

spring:
  application:
    name: CLOUD-CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/JagdishKamdi/config-server
          clone-on-start: true